version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODEL=llama3.1:8b
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      - OLLAMA_MODEL=llama3.1:8b
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - ollama
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data:
